<?php

namespace backend\models\mongo;

use Yii;
use yii\mongodb\Query;
use yii\mongodb\Connection;
use yii\base\InvalidConfigException;

class MetaQuery extends Query {

    /**
     * @var Connection
     */
    protected $_db = null;

    public function setDb($db)
    {
        if (is_string($db)) {
            $db = Yii::$app->get($db);
        } else if (is_array($db)) {
            $db = Yii::createObject($db);
        }

        if ($db instanceof Connection) {
            $this->_db = $db;
        } else {
            throw new InvalidConfigException('传入db类型不正确');
        }
    }

    /**
     * @inheritDoc
     *
     * Query中所有查询方法最终都会调用getCollection(),因而重写该方法获取db的方法
     *
     * @see Query::all()
     */
    public function getCollection($db = null)
    {
        if ($db === null) {
            $db = $this->_db;
        }

        return parent::getCollection($db); // TODO: Change the autogenerated stub
    }
}